In [1]:
import numpy as np
import scipy
import scipy.linalg

1. Решите линейную систему:

In [2]:
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
np.linalg.solve(A, B)

array([-9.2       ,  0.9       ,  6.46666667])

2. Найдите псевдорешение:

In [3]:
A = np.array([[1, 2, -1],
             [3, -4, 0],
             [8, -5, 2],
             [2, 0, -5],
             [11, 4, -7]])

B = np.array([1, 7, 12, 7, 15])

np.linalg.lstsq(A, B)

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  if __name__ == '__main__':


(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

3. Сколько решений имеет линейная система:

In [4]:
A = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])

B = np.array([[12, 2, 1]])

C = np.concatenate((A, B.T), axis=1)
print (C)
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)

[[ 1  2  3 12]
 [ 4  5  6  2]
 [ 7  8  9  1]]


(2, 3)

Так как ранг исходной матрицы A меньше ранга расширенной матрицы C, то система не имеет решения.

Если ноль – то измените вектор правой части так, чтобы система стала совместной, и решите ее.

Заменим число 12 в матрице B на 3.

In [5]:
A = np.array([[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]])

B = np.array([[3, 2, 1]])

C = np.concatenate((A, B.T), axis=1)
print (C)
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)

[[1 2 3 3]
 [4 5 6 2]
 [7 8 9 1]]


(2, 2)

Так как ранг меньше числа неизвестных, то система имеет бесконечное множество решений.

4. Вычислите LU-разложение матрицы:

In [6]:
A = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]])
P, L, U = scipy.linalg.lu(A)

In [7]:
print(P)
print("")
print(L)
print("")
print(U)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]

[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]

[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


После этого придумайте вектор правых частей и решите полученную линейную систему трех уравнений с данной матрицей.

In [8]:
np.linalg.matrix_rank(A, 0.0001)

3

In [9]:
B = np.array([[3, 2, 1]])

In [10]:
C = np.concatenate((A, B.T), axis=1)
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)

(3, 3)

In [11]:
np.linalg.lstsq(A, B.T)

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


(array([[ 3.72685185],
        [-0.18287037],
        [-0.12037037]]),
 array([], dtype=float64),
 3,
 array([82.41767138,  7.1264625 ,  0.73551139]))

5. Найдите нормальное псевдорешение недоопределенной системы:

In [12]:
A = np.array([[1, 2, -1],
             [8, -5, 2]])

B = np.array([1, 12])

Для этого определите функцию Q(x,y,z), равную норме решения, и найдите ее минимум.

In [13]:
def Q(x, y, z):
    return(x**2 + y**2 + z**2)

### !!! пока не понимаю, возможно успею решить до проверки

6.  Найдите одно из псевдорешений вырожденной системы:

In [14]:
A = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
B = np.array([2, 5, 11])
Q, R = np.linalg.qr(A)

print(A)
print(Q)
print(R)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.77635684e-15]]


In [15]:
R1 = R[:2, :2]
R1

array([[-8.1240384 , -9.6011363 ],
       [ 0.        ,  0.90453403]])

In [16]:
B1 = np.dot(np.transpose(Q), B)[:2]
B1

array([-1.21860576e+01,  8.43769499e-15])

In [17]:
X1 = np.linalg.solve(R1, B1)
X1

array([1.50000000e+00, 9.32822279e-15])

In [18]:
X = np.append(X1, 0)
print (X)
np.linalg.norm(X)

[1.50000000e+00 9.32822279e-15 0.00000000e+00]


1.4999999999999896